version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-18.04
    ports:
      - 1433:1433
    env_file:
      - .env
    environment:
      - SA_PASSWORD=$MSSQL_SA_PASSWORD
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver_data:/var/lib/mssql/data

volumes:
  sqlserver_data: {}
